### ISSUE TITLE
Scala 2.12 build

### ISSUE THREAD

**Issue by dbronecki** [maxpsq/google-maps-api-ws-scala-client#7]
Hi,
Could you provide build for Scala 2.12 ?

**Comment by maxpsq** [comment]
Hi mate,

yes it's possible... It's been a while since the last commit on this project so it's definitely time to upgrade it. What would you think about upgrading even the dependencies? The main library on which this client depends on is [dispatch/reboot](https://github.com/dispatch/reboot) and I noticed they provided new builds. I suppose to get on with my work in the next 72 hors, so be patient... in case you cannot possibly wait as long, why don't you just fork the repo and do it yourself? As I wrote in the README page, pull requests are very welcome!

**Comment by dbronecki** [comment]
Sure! I sent you PR, please review it.

**Comment by maxpsq** [comment]
I've just published the artifacts on Sonatype as version 0.3-SNAPSHOT. Follow the updated README file to add the dependencies to your project.
No idea how long will it take to make the artifacts actually downloadable from Sonatype.

Cheers and thanks for your cooperation

**Comment by dbronecki** [comment]
Thanks! Sorry for not updating specs2 - I missed that because I was testing against 2.11.
